### ISSUE TITLE
HowTo: create an user with the API

### ISSUE THREAD

**Issue by ghost** [GreenPix/dilia#10]
The dilia UI does not provide a way to create a new user, you have to send a request directly to the server in order to do that.

This information has to be explained somewhere. I think the README is a good candidate. 

I already said it to @Nemikolh but I create an issue in order to be sure it does not fall into oblivion (:

**Comment by ghost** [comment]
Btw, I can do it if you want me to, it would be a pleasure.

**Comment by Nemikolh** [comment]
It would be very appreciated. :-)

Also if you think of anything else that could be missing from the README, feel free to add it.

**Comment by ghost** [comment]
I push my suggestion directly in your PR, I hope you won’t mind. Feel free to modify it!

**Comment by Nemikolh** [comment]
No problem! I'm fine with this. :)
