### ISSUE TITLE
NODE_ENV variable still should be set

### ISSUE THREAD

**Issue by lthms** [GreenPix/dilia#15]
If `NODE_ENV` is not set for `npm install`, then `npm run server` will fail. Is that a bug?

**Comment by Nemikolh** [comment]
Arf, that's a good question, this is not very user friendly. I'm not sure what is appropriate here. The way the server is built is very different from the web client.

We want to avoid to start a prod server by mistake in dev mode. So we want to make sure the appropriate value has been chosen. Maybe the default for the server should be production then?

What do you think?

**Comment by lthms** [comment]
I think it is a good idea, yes.

**Comment by Nemikolh** [comment]
Ok let's do this. Feel free to submit a PR for this one if you are interested. I have a problem with the  camera in my latest PR (I broke it, again..) which will keep me busy.

**Comment by lthms** [comment]
Will try, yet I am not sure which file I should edit.

**Comment by Nemikolh** [comment]
No worries, have look [here](https://github.com/GreenPix/dilia/blob/master/server/check.ts#L4-L8).
