### ISSUE TITLE
npm: install hangs with npm

### ISSUE THREAD

**Issue by lthms** [GreenPix/dilia#23]
I know, I know I should use vagrant. Yet, I found myself unable to get `npm install` working. This issue is more a question than a real bug.

My version of npm and node are the following:

``` bash
[lethom@ideepad ~]$ node --version
v6.5.0
[lethom@ideepad ~]$ npm --version
3.10.6
```

**Comment by Nemikolh** [comment]
That's a perfectly fine usecase! Even if you use vagrant, you would end up running npm install on the host to get the libraries for autocompletion or even running `npm start`.

Did you wait long enough? When you stopped how many libraries where installed in the `node_modules` folder? Could you have any proxy settings required?

**Comment by lthms** [comment]
I will try again and tell you more about my issue (I recognize this issue is a bit… short, in its current state)

**Comment by Nemikolh** [comment]
No worries! I'm just curious what is going on with `npm`. I have never seen such a thing before but this is also the first time that someone is using a Mac. ;) So we might learn something about developing on this platform and make it easier for Mac users.

**Comment by lthms** [comment]
Okay so I will try again now with the current version.

**Comment by lthms** [comment]
Upgrading to node 6.6.0 seems to have fixed the issue.
