### ISSUE TITLE
Chipset image format is not handled properly.

### ISSUE THREAD

**Issue by Nemikolh** [GreenPix/dilia#40]
We should make sure before the upload that the image format is RGBA. Eventually, performing a conversion within the browser.

**Comment by lthms** [comment]
A first (and quick) thing to do can be to check the image format and issue a warning if it is not correct. I am not sure this is a top priority issue. What do you think?

**Comment by Nemikolh** [comment]
It was the source of the problem @Azamung has last night. I looked at it a bit this morning and its seems that there's nothing we can do in the browser... Apart from letting the user specify it. The alternative is to do that part in the server. I guess this is part of the header in the image file.
